### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Follow-spaceX** [Tyler98ky/tensorFlow-MLP-NSLKDD#1]
ValueError: tcp value not in ("'tcp'", "'udp'", "'icmp'")

**Comment by tylerhoward15** [comment]
The scipy library for loading arff files has some bugs regarding white-space. The arff files provided by the NSL-KDD data-set has some inconsistencies with how it utilized white-space in the file.

I had to correct the data and remove unnecessary white-space, and these corrections are reflected in the arff files in this repo. In summary, use the arff files provided in this repo and you shouldn't have any problems. If you use the original files provided with NSL-KDD, this bug will occur when using `loadarff` from scipy.
